spring:
application:
    name: apigateway-service
cloud:
    gateway:
    routes:
        - id: searchApi
        uri: http://localhost:8082/
        predicates: #조건절
            - Path=/v1/search/**
 