spring:
  application:
    name: gateway
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/search/**
      url: http://localhost:8081
    else:
      stripPrefix: false
      path: /**
      url: http://localhost:8081