server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/77kkyu/spring-cloud-msa
          search-paths: server-configs
          default-label: main
        encrypt:
          enabled: false
  application:
    name: configure-server

# 암호화 http://localhost:8081/encrypt Post로 문자열 전송
# 테스트 결과 key: kkyu-encrypt-key랑 같이 해싱을 해서 암호화키를 만들어 내는 것 같음
# key를 변경했을 경우에 @Value("${spring.message}") 암호화된 메세지 자체를 가져오지 못한다(컴파일 에러)
encrypt:
  key: kkyu-encrypt-key


#        native: #
#          search-locations: file:///${user.home}/server-configs # window - C:\Users\???\server-configs
#          search-locations: file://${user.home}/server-configs # mac, linux
#          search-locations: classpath:/server-configs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka